config/routes.rb
Rails.application.routes.draw do
  get 'agreements/create'
  resources :comments
  devise_for :users, controllers: {
  	registrations: 'users/registrations'
  }
  root to: 'joboffers#index'
  get 'users/show'

  resources :agreements, only: :index
  resources :joboffers

  resources :joboffers, only: :show do
  	resources :agreements, only: :create
  end

  resources :joboffers, only: :show do
    resources :comments
  end
end
  

app/models/joboffer.rb
class Joboffer < ApplicationRecord
  belongs_to :user
  has_many :agreements
  has_many :users, through: :agreements
  has_many :comments
  has_one_attached :image1
  has_one_attached :image2
  has_one_attached :image3
  has_one_attached :image4
  has_one_attached :image5
  has_one_attached :image6

  validates :title, presence: true
  validates :description, presence: true
  # validates :skill_id, presence: true
  validates :image1, presence: false
  validates :image2, presence: false
  validates :image3, presence: false
  validates :image4, presence: false
  validates :image5, presence: false
  validates :image6, presence: false

end

app/controllers/joboffers_controller.rb
class JoboffersController < ApplicationController
  before_action :set_joboffer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :show]
  load_and_authorize_resource
  # GET /joboffers
  # GET /joboffers.json
  def index
    @joboffers = Joboffer.all.order('created_at DESC')
  end

  # GET /joboffers/1
  # GET /joboffers/1.json
  def show
    @comment = Comment.new
    @comments = Comment.all.order('created_at DESC')
  end

  # GET /joboffers/new
  def new

  end

  # GET /joboffers/1/edit
  def edit
  end

  def agreement
  end

  # POST /joboffers
  # POST /joboffers.json
  def create
    @joboffer = Joboffer.new(joboffer_params)
    @joboffer.user = current_user
    respond_to do |format|
      if @joboffer.save
        format.html { redirect_to @joboffer, notice: 'Joboffer was successfully created.' }
        format.json { render :show, status: :created, location: @joboffer }
      else
        format.html { render :new }
        format.json { render json: @joboffer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /joboffers/1
  # PATCH/PUT /joboffers/1.json
  def update
    respond_to do |format|
      if @joboffer.update(joboffer_params)
        format.html { redirect_to @joboffer, notice: 'Tu Aviso fue creado exitosamente.' }
        format.json { render :show, status: :ok, location: @joboffer }
      else
        format.html { render :edit }
        format.json { render json: @joboffer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /joboffers/1
  # DELETE /joboffers/1.json
  def destroy
    @joboffer.destroy
    respond_to do |format|
      format.html { redirect_to joboffers_url, notice: 'Tu Aviso fue eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_joboffer
      @joboffer = Joboffer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def joboffer_params
      params.require(:joboffer).permit(:title, :description, :photo, :budget, :start_date, :end_date, :location_id, :skill_id, :user_id, :image1, :image2, :image3, :image4, :image5, :image6 )
    end
end

app/helpers/joboffers_helper.rb
module JoboffersHelper
end

app/views/joboffers/_form.html.erb
<%= form_with(model: joboffer, local: true) do |form| %>
  <% if joboffer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(joboffer.errors.count, "error") %> prohibited this joboffer from being saved:</h2>

      <ul>
      <% joboffer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

 <div class="field">
    <%= form.label :image1 %>
    <%= form.file_field :image1 %>
  </div>

  <div class="field">
    <%= form.label :image2 %>
    <%= form.file_field :image2 %>
  </div>

  <div class="field">
    <%= form.label :image3 %>
    <%= form.file_field :image3 %>
  </div>

    <div class="field">
    <%= form.label :image4 %>
    <%= form.file_field :image4 %>
  </div>

  <div class="field">
    <%= form.label :image5 %>
    <%= form.file_field :image5 %>
  </div>

  <div class="field">
    <%= form.label :image6 %>
    <%= form.file_field :image6 %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo %>
    <%= form.text_field :photo %>
  </div>

  <div class="field">
    <%= form.label :budget %>
    <%= form.number_field :budget %>

  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.datetime_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.datetime_select :end_date %>
  </div>

  <div class="field">
    <%= form.label :location_id %>
    <%= form.number_field :location_id %>
  </div>

  <div class="field">
    <%= form.label :skill_id %>
    <%= form.number_field :skill_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= current_user.name %>
    <%= current_user.last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/joboffers/edit.html.erb
<h1>Editing Joboffer</h1>

<%= render 'form', joboffer: @joboffer %>

<%= link_to 'Show', @joboffer %> |
<%= link_to 'Back', joboffers_path %>

app/views/joboffers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Joboffers</h1>

<div class="container-fluid">
    <%= render 'layouts/navbar' %>
    <%= link_to "Nuevo Aviso", new_joboffer_path, class:'btn btn-warning' %>
    <div class="row">
      <% @joboffers.each_slice(3) do |row| %>
        <% row.each do |joboffer| %>
          <div class="col">
            <div style="margin: 10px" class="card border bg-light">  
              <div style="padding: 10px" class="body">
                <tr>
                   
                     <td><%= image_tag joboffer.image1, size:'360x230', class: "card-img-top" %></td>
                      <td><h5><%= joboffer.title %></h5></td>
                      
                      <td><p class="text-break"><%=h truncate(joboffer.description, :length => 250) %></p></td>
                      <td><p><%= joboffer.location_id %></p></td>
                      <td><p>
                            <strong >Usuario:</strong>
                            <%= joboffer.user.name %>
                            <%= joboffer.user.last_name %>
                          </p>
                        </td>
                      <td><%= link_to "Mostrar", joboffer_path(joboffer), class: 'btn btn-success' %></td>
                      <td>
                        <% if can?(:edit, joboffer) %>
                        <%= link_to 'Editar', edit_joboffer_path(joboffer), class: 'btn btn-info' %>
                        <% end %>
                      </td>
                      <td>
                        <% if can?(:destroy, joboffer) %>
                        <%= link_to 'Eliminar', joboffer, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
                          <% end %>
                      </td>
                    </tr>
                
              </div>
            </div>
          </div>
        <% end %>
        <div class="w-100"> </div>
      <% end %>
    </div>

    <%= link_to "Nuevo Aviso", new_joboffer_path, class:'btn btn-warning' %>
 

app/views/joboffers/new.html.erb
<h1>New Joboffer</h1>

<%= render 'form', joboffer: @joboffer %>

<%= link_to 'Back', joboffers_path %>

app/views/joboffers/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="card-columns">

    <div class="card">
      <a href="" data-toggle="modal" data-target="#exampleModal1">
        <% if @joboffer.image1.attached? %>
          <%= image_tag @joboffer.image1, size:'360x230', class: "card-img-top"  %>
        <% end %>
      </a>
    </div>
    <div class="modal fade" id="exampleModal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <button type="button" class="close mr-1" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
      <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
        <% if @joboffer.image1.attached? %>
          <%= image_tag @joboffer.image1, class: "img-fluid rounded card-img-top"  %>
        <% end %>
      </div>
    </div>

    <div class="card">
      <a href="" data-toggle="modal" data-target="#exampleModal4">
        <% if @joboffer.image4.attached? %>
          <%= image_tag @joboffer.image4, size:'360x230', class: "card-img-top"  %>
        <% end %>
      </a>
    </div>
    <div class="modal fade" id="exampleModal4" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <button type="button" class="close mr-1" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
      <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
        <% if @joboffer.image4.attached? %>
          <%= image_tag @joboffer.image4, class: "img-fluid rounded card-img-top"  %>
        <% end %>
      </div>
    </div>

    <div class="card">
      <a href="" data-toggle="modal" data-target="#exampleModal2">
        <% if @joboffer.image2.attached? %>
          <%= image_tag @joboffer.image2, size:'360x230', class: "card-img-top"  %>
        <% end %>
      </a>
    </div>
    <div class="modal fade" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <button type="button" class="close mr-1" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
      <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
        <% if @joboffer.image2.attached? %>
          <%= image_tag @joboffer.image2, class: "img-fluid rounded card-img-top"  %>
        <% end %>
      </div>
    </div>

    <div class="card">
      <a href="" data-toggle="modal" data-target="#exampleModal5">
        <% if @joboffer.image5.attached? %>
          <%= image_tag @joboffer.image5, size:'360x230', class: "card-img-top"  %>
        <% end %>
      </a>
    </div>
    <div class="modal fade" id="exampleModal5" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <button type="button" class="close mr-1" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
      <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
        <% if @joboffer.image5.attached? %>
          <%= image_tag @joboffer.image5, class: "img-fluid rounded card-img-top"  %>
        <% end %>
      </div>
    </div>
    
    <div class="card">
      <a href="" data-toggle="modal" data-target="#exampleModal3">
        <% if @joboffer.image3.attached? %>
          <%= image_tag @joboffer.image3, size:'360x230', class: "card-img-top"  %>
        <% end %>
      </a>
    </div>
    <div class="modal fade" id="exampleModal3" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <button type="button" class="close mr-1" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
      <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
        <% if @joboffer.image3.attached? %>
          <%= image_tag @joboffer.image3, class: "img-fluid rounded card-img-top"  %>
        <% end %>
      </div>
    </div>

    <div class="card">
      <a href="" data-toggle="modal" data-target="#exampleModal6">
        <% if @joboffer.image6.attached? %>
          <%= image_tag @joboffer.image6, size:'360x230', class: "card-img-top"  %>
        <% end %>
      </a>
    </div>
    <div class="modal fade" id="exampleModal6" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <button type="button" class="close mr-1" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
      <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
        <% if @joboffer.image6.attached? %>
          <%= image_tag @joboffer.image6, class: "img-fluid rounded card-img-top"  %>
        <% end %>
      </div>
    </div>

  
  </div>
</div>

<p>
  <strong>Photo:</strong>
  <div class="card-columns">
    <div class="card rounded mx-auto d-block">
        <a href="" data-toggle="modal" data-target="#exampleModal7">
          <%= image_tag @joboffer.photo, size:'360x230', class: "card-img-top"  %>
        </a>
      </div>
      
      <div class="modal fade" id="exampleModal7" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <button type="button" class="close mr-1" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
        <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
          <%= image_tag @joboffer.photo, class: "img-fluid rounded card-img-top"  %>
          
        </div>
      </div>
    </div>
</p>

<h3>
  <strong>Title:</strong>
  <%= @joboffer.title %>
</h3>

<p class="text-break">
  <strong>Description:</strong>
  <%= @joboffer.description %>
</p>

<p>
  <strong>Budget:</strong>
  <%= @joboffer.budget %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @joboffer.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @joboffer.end_date %>
</p>

<p>
  <strong>Location:</strong>
  <%= @joboffer.location_id %>
</p>

<p>
  <strong>Skill:</strong>
  <%= @joboffer.skill_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @joboffer.user.name %>
  <%= @joboffer.user.last_name %>
</p>

<%= link_to 'Edit', edit_joboffer_path(@joboffer) %> |
<%= link_to 'Back', joboffers_path %>

<%= link_to 'Cerrar trato', joboffer_agreements_path(@joboffer), class: 'btn btn-success', method: :post %>

<div class="container-fluid">
  <div class="jumbotron">
<h1 class="text-center">Comentarios</h1>
</div>



<p id="notice"><%= notice %></p>
  
<div class="container-fluid">
<div class="row">

<div class="col-sm-5 col-md-9">
  <div class="table table-striped table-bordered">
     <table class="table">
    <thead>
      <tr>
        <th scope="col">User</th>
        <th scope="col">Content</th>
        <th scope="col">Price</th>
      </tr>
    </thead>

    <tbody>
      <% @comments.each do |comment| %>
        <tr class="border border-dark">
          <td><%= comment.user_id %></td>
          <td><%= comment.content %></td>
          <td><%= comment.price %></td>
          <td><%= link_to 'Edit', edit_comment_path(comment), class: 'btn btn-info' %></td>
          <td><%= link_to 'Destroy', comment, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
</div>



  <div class="col-md-3 border border-info">
    <div class="sticky-top pagination justify-content-center" style="margin-top: 50px">
    <%= form_with(model: @comment, local: true) do |form| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h6 class="text-center">Nuevo Comentario</h6>
  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
    <%= current_user.name %>
    <%= current_user.last_name %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :joboffer_id %>
    <%= form.number_field :joboffer_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
  </div>
  </div>
</div>
</div>


</div>